---
title: "CKD"
output:
  html_document:
    df_print: paged
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  cache = TRUE
)
```

## Call the package
```{r set up}
library(devtools)
load_all()
```

## body mass index (BMI) - Chronic kidney disease
```{r}
a <- MultiAncestrySummarySet$new(
  exposure_ids=c("ieu-a-2", "bbj-a-1"), 
  outcome_ids=c("ieu-a-1105", "bbj-a-60"), 
  pops=c("EUR", "EAS"),
  bfiles=c("/Users/yc16575/MR.TRAM/R/EUR", "/Users/yc16575/MR.TRAM/R/EAS"), 
  plink = genetics.binaRies::get_plink_binary(), 
  radius=50000, 
  clump_pop="EAS"
)
a$extract_instruments()

#Check the instruments for the exposures and the outcomes
a$check_phenotypes(ids=a$exposure_ids)
a$check_phenotypes(ids=a$outcome_ids)
a$standardise_units(exp=a$instrument_raw, out=NULL)

#Standardise the beta and the se
a$check_phenotypes(ids=NULL, after_standardised=a$standardised_exposure)
a$estimate_instrument_specificity(a$standardised_exposure)

#Extract instruments for the outcomes
a$make_outcome_data(exp=a$standardised_exposure, p_exp=1)
a$standardise_units(exp=NULL, out=a$instrument_outcome)

#harmonise the datasets
a$harmonised_dat(exp=a$standardised_exposure, out=a$standardised_outcome)

#run sem-mr
a$perform_basic_sem()

#Extract other instruments
##based on the regions
suppressMessages(a$extract_instrument_regions())
a$scan_regional_instruments()
a$estimate_instrument_specificity(a$instrument_maxz)
a$standardise_units(exp=a$instrument_maxz)
a$make_outcome_data(exp=a$standardised_exposure, p_exp=1)
a$standardise_units(exp=NULL, out=a$instrument_outcome)
a$harmonised_dat(exp=a$standardised_exposure, out=a$standardised_outcome)
a$perform_basic_sem()

##susie
a$regional_ld_matrices()
a$susie_finemap_regions()
a$estimate_instrument_specificity(a$instrument_susie)
a$standardise_units(exp=a$instrument_susie)
a$make_outcome_data(exp=a$standardised_exposure, p_exp=1)
a$standardise_units(exp=NULL, out=a$instrument_outcome)
a$harmonised_dat(exp=a$standardised_exposure, out=a$standardised_outcome)
a$perform_basic_sem()
```


# SBP-CHD
Exposures: SBP (EUR: systolic blood pressure; International Consortium of Blood Pressure, EAS: BBJ); 
Outcomes: CHD (EUR-EAS)
```{r}
b <- MultiAncestrySummarySet$new(
  exposure_ids=c("ieu-b-38", "bbj-a-52"), 
  outcome_ids=c("ieu-a-1105", "bbj-a-60"), 
  pops=c("EUR", "EAS"),
  bfiles=c("/Users/yc16575/MR.TRAM/R/EUR", "/Users/yc16575/MR.TRAM/R/EAS"), 
  plink = genetics.binaRies::get_plink_binary(), 
  radius=50000, 
  clump_pop="EAS"
)
b$extract_instruments()

#Check the instruments for the exposures and the outcomes
b$check_phenotypes(ids=b$exposure_ids)
b$check_phenotypes(ids=b$outcome_ids)
b$standardise_units(exp=b$instrument_raw, out=NULL)

#Standardise the beta and the se
b$check_phenotypes(ids=NULL, after_standardised=b$standardised_exposure)
b$estimate_instrument_specificity(b$standardised_exposure)

#Extract instruments for the outcomes
b$make_outcome_data(exp=b$standardised_exposure, p_exp=1)
b$standardise_units(exp=NULL, out=b$instrument_outcome)

#harmonise the datasets
b$harmonised_dat(exp=b$standardised_exposure, out=b$standardised_outcome)

#run sem-mr
b$perform_basic_sem()

#Extract other instruments
##based on the regions
suppressMessages(b$extract_instrument_regions())
b$scan_regional_instruments()
b$estimate_instrument_specificity(b$instrument_maxz)
b$standardise_units(exp=b$instrument_maxz)
b$make_outcome_data(exp=b$standardised_exposure, p_exp=1)
b$standardise_units(exp=NULL, out=b$instrument_outcome)
b$harmonised_dat(exp=b$standardised_exposure, out=b$standardised_outcome)
b$perform_basic_sem()

##susie
b$regional_ld_matrices()
b$susie_finemap_regions()
b$estimate_instrument_specificity(b$instrument_susie)
b$standardise_units(exp=b$instrument_susie)
b$make_outcome_data(exp=b$standardised_exposure, p_exp=1)
b$standardise_units(exp=NULL, out=b$instrument_outcome)
b$harmonised_dat(exp=b$standardised_exposure, out=b$standardised_outcome)
b$perform_basic_sem()

```


## high density lipoprotein cholesterol (HDL) - CKD
```{r}
c <- MultiAncestrySummarySet$new(
  exposure_ids=c("ieu-a-299", "bbj-a-24"), 
  outcome_ids=c("ieu-a-1105", "bbj-a-60"), 
  pops=c("EUR", "EAS"),
  bfiles=c("/Users/yc16575/MR.TRAM/R/EUR", "/Users/yc16575/MR.TRAM/R/EAS"), 
  plink = genetics.binaRies::get_plink_binary(), 
  radius=50000, 
  clump_pop="EAS"
)
c$extract_instruments()

#Check the instruments for the exposures and the outcomes
c$check_phenotypes(ids=c$exposure_ids)
c$check_phenotypes(ids=c$outcome_ids)
c$standardise_units(exp=c$instrument_raw, out=NULL)

#Standardise the beta and the se
c$check_phenotypes(ids=NULL, after_standardised=c$standardised_exposure)
c$estimate_instrument_specificity(c$standardised_exposure)

#Extract instruments for the outcomes
c$make_outcome_data(exp=c$standardised_exposure, p_exp=1)
c$standardise_units(exp=NULL, out=c$instrument_outcome)

#harmonise the datasets
c$harmonised_dat(exp=c$standardised_exposure, out=c$standardised_outcome)

#run sem-mr
c$perform_basic_sem()

#Extract other instruments
##based on the regions
suppressMessages(c$extract_instrument_regions())
c$scan_regional_instruments()
c$estimate_instrument_specificity(c$instrument_maxz)
c$standardise_units(exp=c$instrument_maxz)
c$make_outcome_data(exp=c$standardised_exposure, p_exp=1)
c$standardise_units(exp=NULL, out=c$instrument_outcome)
c$harmonised_dat(exp=c$standardised_exposure, out=c$standardised_outcome)
c$perform_basic_sem()

##susie
c$regional_ld_matrices()
c$susie_finemap_regions()
c$estimate_instrument_specificity(c$instrument_susie)
c$standardise_units(exp=c$instrument_susie)
c$make_outcome_data(exp=c$standardised_exposure, p_exp=1)
c$standardise_units(exp=NULL, out=c$instrument_outcome)
c$harmonised_dat(exp=c$standardised_exposure, out=c$standardised_outcome)
c$perform_basic_sem()
```

## apolipoprotein A-I
```{r}
d <- MultiAncestrySummarySet$new(
  exposure_ids=c("ieu-b-107", "ukb-e-30630_EAS"), 
  outcome_ids=c("ieu-a-1105", "bbj-a-60"), 
  pops=c("EUR", "EAS"),
  bfiles=c("/Users/yc16575/MR.TRAM/R/EUR", "/Users/yc16575/MR.TRAM/R/EAS"), 
  plink = genetics.binaRies::get_plink_binary(), 
  radius=50000, 
  clump_pop="EAS"
)
d$extract_instruments()

#Check the instruments for the exposures and the outcomes
d$check_phenotypes(ids=d$exposure_ids)
d$check_phenotypes(ids=d$outcome_ids)
d$standardise_units(exp=d$instrument_raw, out=NULL)

#Standardise the beta and the se
d$check_phenotypes(ids=NULL, after_standardised=d$standardised_exposure)
d$estimate_instrument_specificity(d$standardised_exposure)

#Extract instruments for the outcomes
d$make_outcome_data(exp=d$standardised_exposure, p_exp=1)
d$standardise_units(exp=NULL, out=d$instrument_outcome)

#harmonise the datasets
d$harmonised_dat(exp=d$standardised_exposure, out=d$standardised_outcome)

#run sem-mr
d$perform_basic_sem()

#Extract other instruments
##based on the regions
suppressMessages(d$extract_instrument_regions())
d$scan_regional_instruments()
d$estimate_instrument_specificity(d$instrument_maxz)
d$standardise_units(exp=d$instrument_maxz)
d$make_outcome_data(exp=d$standardised_exposure, p_exp=1)
d$standardise_units(exp=NULL, out=d$instrument_outcome)
d$harmonised_dat(exp=d$standardised_exposure, out=d$standardised_outcome)
d$perform_basic_sem()

##susie
d$regional_ld_matrices()
d$susie_finemap_regions()
d$estimate_instrument_specificity(d$instrument_susie)
d$standardise_units(exp=d$instrument_susie)
d$make_outcome_data(exp=d$standardised_exposure, p_exp=1)
d$standardise_units(exp=NULL, out=d$instrument_outcome)
d$harmonised_dat(exp=d$standardised_exposure, out=d$standardised_outcome)
d$perform_basic_sem()
```

## lipoprotein A
```{R}
e <- MultiAncestrySummarySet$new(
  exposure_ids=c("ieu-b-107", "ukb-e-30630_EAS"), 
  outcome_ids=c("ieu-a-1105", "bbj-a-60"), 
  pops=c("EUR", "EAS"),
  bfiles=c("/Users/yc16575/MR.TRAM/R/EUR", "/Users/yc16575/MR.TRAM/R/EAS"), 
  plink = genetics.binaRies::get_plink_binary(), 
  radius=50000, 
  clump_pop="EAS"
)
e$extract_instruments()

#Check the instruments for the exposures and the outcomes
e$check_phenotypes(ids=e$exposure_ids)
e$check_phenotypes(ids=e$outcome_ids)
e$standardise_units(exp=e$instrument_raw, out=NULL)

#Standardise the beta and the se
e$check_phenotypes(ids=NULL, after_standardised=e$standardised_exposure)
e$estimate_instrument_specificity(e$standardised_exposure)

#Extract instruments for the outcomes
e$make_outcome_data(exp=e$standardised_exposure, p_exp=1)
e$standardise_units(exp=NULL, out=e$instrument_outcome)

#harmonise the datasets
e$harmonised_dat(exp=e$standardised_exposure, out=e$standardised_outcome)

#run sem-mr
e$perform_basic_sem()

#Extract other instruments
##based on the regions
suppressMessages(e$extract_instrument_regions())
e$scan_regional_instruments()
e$estimate_instrument_specificity(e$instrument_maxz)
e$standardise_units(exp=e$instrument_maxz)
e$make_outcome_data(exp=e$standardised_exposure, p_exp=1)
e$standardise_units(exp=NULL, out=e$instrument_outcome)
e$harmonised_dat(exp=e$standardised_exposure, out=e$standardised_outcome)
e$perform_basic_sem()

##susie
e$regional_ld_matrices()
e$susie_finemap_regions()
e$estimate_instrument_specificity(e$instrument_susie)
e$standardise_units(exp=e$instrument_susie)
e$make_outcome_data(exp=e$standardised_exposure, p_exp=1)
e$standardise_units(exp=NULL, out=e$instrument_outcome)
e$harmonised_dat(exp=e$standardised_exposure, out=e$standardised_outcome)
e$perform_basic_sem()
```

## type 2 diabetes (T2D)
```{r}
f <- MultiAncestrySummarySet$new(
  exposure_ids=c("ieu-a-23", "bbj-a-77"), 
  outcome_ids=c("ieu-a-1105", "bbj-a-60"), 
  pops=c("EUR", "EAS"),
  bfiles=c("/Users/yc16575/MR.TRAM/R/EUR", "/Users/yc16575/MR.TRAM/R/EAS"), 
  plink = genetics.binaRies::get_plink_binary(), 
  radius=50000, 
  clump_pop="EAS"
)
f$extract_instruments()

#Check the instruments for the exposures and the outcomes
f$check_phenotypes(ids=f$exposure_ids)
f$check_phenotypes(ids=f$outcome_ids)
f$standardise_units(exp=f$instrument_raw, out=NULL)

#Standardise the beta and the se
f$check_phenotypes(ids=NULL, after_standardised=f$standardised_exposure)
f$estimate_instrument_specificity(f$standardised_exposure)

#Extract instruments for the outcomes
f$make_outcome_data(exp=f$standardised_exposure, p_exp=1)
f$standardise_units(exp=NULL, out=f$instrument_outcome)

#harmonise the datasets
f$harmonised_dat(exp=f$standardised_exposure, out=f$standardised_outcome)

#run sem-mr
f$perform_basic_sem()

#Extract other instruments
##based on the regions
suppressMessages(f$extract_instrument_regions())
f$scan_regional_instruments()
f$estimate_instrument_specificity(f$instrument_maxz)
f$standardise_units(exp=f$instrument_maxz)
f$make_outcome_data(exp=f$standardised_exposure, p_exp=1)
f$standardise_units(exp=NULL, out=f$instrument_outcome)
f$harmonised_dat(exp=f$standardised_exposure, out=f$standardised_outcome)
f$perform_basic_sem()

##susie
f$regional_ld_matrices()
f$susie_finemap_regions()
f$estimate_instrument_specificity(f$instrument_susie)
f$standardise_units(exp=f$instrument_susie)
f$make_outcome_data(exp=f$standardised_exposure, p_exp=1)
f$standardise_units(exp=NULL, out=f$instrument_outcome)
f$harmonised_dat(exp=f$standardised_exposure, out=f$standardised_outcome)
f$perform_basic_sem()
```


