---
title: "Scaling; empirical results"
output:
  html_document:
    df_print: paged
---


## phenotypes that showed substantial differences across the populations.

Load the package:
```{r}
library(devtools)
load_all()
```

## BMI - TC
Load the file:
```{r}
load("/Users/yc16575/CAMERA/examples/examples_bmi_tc.rdata")

y <- a
a$import(y)
a <- CAMERA$new()
a$import(y)
```

Check unit information between the populations:
```{r}
a$check_phenotypes(ids=a$exposure_ids)
a$check_phenotypes(ids=a$outcome_ids)
# Unit info are missing: Does it require standardisation?
```

Betas and SEs were standardised: 
1) SD standardisation; 
2) Scale beta difference between the populations
```{r}
# INSTRUMENTS MAXZ
## without standardisation / scaling
a$make_outcome_data(exp=a$instrument_maxz)
a$harmonised_dat(exp=a$instrument_maxz, out=a$instrument_outcome)
a$perform_basic_sem()

## SD standardisation; 
a$standardise_data(dat=a$instrument_maxz, standardise_unit=TRUE)
a$make_outcome_data(exp=a$standardised_instrument_maxz)
a$standardise_data(dat=a$instrument_outcome, standardise_unit=TRUE)
a$harmonised_dat(exp=a$standardised_instrument_maxz, out=a$standardised_outcome)
a$perform_basic_sem()

## SD standardisation and beta scaling
a$standardise_data(dat=a$instrument_maxz, standardise_unit=TRUE, standardise_scale=TRUE)
a$make_outcome_data(exp=a$standardised_instrument_maxz)
a$standardise_data(dat=a$instrument_outcome, standardise_unit=TRUE)
a$harmonised_dat(exp=a$standardised_instrument_maxz, out=a$standardised_outcome)
a$perform_basic_sem()

```
