---
title: "Tutorial"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Tutorial}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(CAMERA)
```


overview
- initialise with traits to be analysed
- check the scale of those phenotypes
- extract instruments

BMI on CHD

```{r}
bfile_dir <- "/Users/gh13047/repo/opengwas-api-internal/opengwas-api/app/ld_files"
x <- CAMERA$new(
  exposure_ids=c("ukb-e-23104_CSA", "ukb-e-21001_AFR", "ukb-b-19953", "bbj-a-1"), 
  outcome_ids=c("ukb-e-411_CSA", "ukb-e-411_AFR", "ieu-a-7", "bbj-a-109"), 
  pops = c("SAS", "AFR", "EUR", "EAS"),
  bfiles=file.path(bfile_dir, c("SAS", "AFR", "EUR", "EAS")),
  plink = genetics.binaRies::get_plink_binary(), 		
  radius=50000, 
  clump_pop="EUR"
)
x
```

Check phenotypes

```{r}
x$check_phenotypes(ids=x$exposure_ids)
```

```{r}
x$extract_instruments()
str(x$instrument_raw)
```


```{r}
x$instrument_heterogeneity(x$instrument_raw)
x$estimate_instrument_specificity(x$instrument_raw, alpha = "bonferroni")
```


```{r}
x$make_outcome_data()
```

```{r}
load("bmi_regions.rdata")
load_all()
x <- y
y <- CAMERA$new()
y$import(x)
y$set_summary()
y$estimate_instrument_specificity(x$instrument_raw, alpha = "bonferroni") %>% as.data.frame
y$instrument_specificity$distinct %>% table
y$instrument_heterogeneity()
# y$harmonised_dat(exp=y$instrument_raw, out=y$instrument_outcome)
y$harmonise()
head(y$harmonised_dat_sem)
dim(y$harmonised_dat_sem)
head(y$harmonised_dat)
dim(y$harmonised_dat)
y$cross_estimate()
y$plot_cross_estimate()


y$estimate_instrument_heterogeneity_per_variant()
y

table(y$instrument_heterogeneity_per_variant$Qpval < 0.05)
table(p.adjust(y$instrument_heterogeneity_per_variant$Qpval, "fdr") < 0.05)

y$mrgxe()
y$mrgxe_plot()


y$mrgxe_res
hist(y$mrgxe_res$a)
hist(y$mrgxe_res$b)


instrument_heterogeneity(y$harmonised_dat)



```

```{r}
y$extract_instrument_regions()
save(y, file="bmi_regions.rdata")
y$regional_ld_matrices()
```

```{r}
y$perform_basic_sem()
```


Perform Interaction model

Perform GxE for outliers


Data construction

gx=instruments for each X
gx1 = gx from all X

gy=instruments for each y
gy1 = g1 from all Y

gx_regions = regions around each X instrument





```{r}

```


```{r}

```
