---
title: "Examples"
author: "Yoonsu Cho"
date: "28/05/2021"
output: html_document
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  cache = FALSE
)
```

# Call the package
```{r set up}
library(devtools)
load_all()
```

## CRP-CHD
```{r}
a <- MultiAncestrySummarySet$new(
      exposure_ids=c("ieu-b-35", "bbj-a-14"),
      outcome_ids=c("ieu-a-7", "bbj-a-109"), 
      pops=c("EUR", "EAS"),
      bfiles=c("/Users/yc16575/OneDrive - University of Bristol/EUR", "/Users/yc16575/OneDrive - University of Bristol/EAS"), 		
  		plink = genetics.binaRies::get_plink_binary(), 		
  		radius=50000, 
  		clump_pop="EAS"
	)
a$check_phenotypes(ids=a$exposure_ids)
a$check_phenotypes(ids=a$outcome_ids)

a$extract_instruments()
a$estimate_instrument_specificity(a$instrument_raw)

a$standardise_units(exp=a$instrument_raw)
a$estimate_instrument_specificity(a$standardised_exposure)
a$check_phenotypes(ids=NULL, after_standardised=a$standardised_exposure)

a$make_outcome_data(exp=a$instrument_raw, p_exp=1)
a$harmonised_dat(exp=a$instrument_raw, out=a$instrument_outcome)
a$perform_basic_sem()

a$make_outcome_data(exp=a$standardised_exposure, p_exp=1)
a$harmonised_dat(exp=a$standardised_exposure, out=a$instrument_outcome)
a$perform_basic_sem()

suppressMessages(a$extract_instrument_regions())
a$scan_regional_instruments()
a$plot_regional_instruments(instruments=a$instrument_maxz)

a$estimate_instrument_specificity(a$instrument_maxz)
a$standardise_units(exp=a$instrument_maxz)
a$estimate_instrument_specificity(a$standardised_exposure)

a$make_outcome_data(exp=a$standardised_exposure, p_exp=1)
a$harmonised_dat(exp=a$standardised_exposure, out=a$instrument_outcome)
a$perform_basic_sem()

suppressWarnings(a$regional_ld_matrices())
suppressWarnings(a$susie_finemap_regions())
a$estimate_instrument_specificity(a$instrument_susie)
a$standardise_units(exp=a$instrument_susie)
a$make_outcome_data(exp=a$standardised_exposure, p_exp=1)
a$harmonised_dat(exp=a$standardised_exposure, out=a$instrument_outcome)
a$perform_basic_sem()

```


## Triglyceride-Type 2 diabetes
```{r}
b <- MultiAncestrySummarySet$new


b$check_phenotypes(ids=b$exposure_ids)
b$check_phenotypes(ids=b$outcome_ids)

b$extract_instruments()
b$estimate_instrument_specificity(b$instrument_raw)

b$standardise_units(exp=b$instrument_raw)
b$estimate_instrument_specificity(b$standardised_exposure)
b$check_phenotypes(ids=NULL, after_standardised=b$standardised_exposure)

b$make_outcome_data(exp=b$instrument_raw, p_exp=1)
b$harmonised_dat(exp=b$instrument_raw, out=b$instrument_outcome)
b$perform_basic_sem()

b$make_outcome_data(exp=b$standardised_exposure, p_exp=1)
b$harmonised_dat(exp=b$standardised_exposure, out=b$instrument_outcome)
b$perform_basic_sem()

suppressMessages(b$extract_instrument_regions())
b$scan_regional_instruments()
b$plot_regional_instruments(instruments=b$instrument_maxz)

b$estimate_instrument_specificity(b$instrument_maxz)
b$standardise_units(exp=b$instrument_maxz)
b$estimate_instrument_specificity(b$standardised_exposure)

b$make_outcome_data(exp=b$standardised_exposure, p_exp=1)
b$harmonised_dat(exp=b$standardised_exposure, out=b$instrument_outcome)
b$perform_basic_sem()

suppressWarnings(b$regional_ld_matrices())
suppressWarnings(b$susie_finemap_regions())
b$estimate_instrument_specificity(b$instrument_susie)
b$standardise_units(exp=b$instrument_susie)
b$make_outcome_data(exp=b$standardised_exposure, p_exp=1)
b$harmonised_dat(exp=b$standardised_exposure, out=b$instrument_outcome)
b$perform_basic_sem()
```

 
## BMI-Type 2 diabetes
```{r}
c <- MultiAncestrySummarySet$new(
      exposure_ids=c("ieu-a-2", "bbj-a-1"), 
      outcome_ids=c("ieu-a-23", "bbj-a-77"), 
      pops=c("EUR", "EAS"),
      bfiles=c("/Users/yc16575/OneDrive - University of Bristol/EUR", "/Users/yc16575/OneDrive - University of Bristol/EAS"), 		
  		plink = genetics.binaRies::get_plink_binary(), 		
  		radius=50000, 
  		clump_pop="EAS"
)
c$check_phenotypes(ids=c$exposure_ids)
c$check_phenotypes(ids=c$outcome_ids)

c$extract_instruments()
c$estimate_instrument_specificity(c$instrument_raw)

c$standardise_units(exp=c$instrument_raw)
c$estimate_instrument_specificity(c$standardised_exposure)
c$check_phenotypes(ids=NULL, after_standardised=c$standardised_exposure)

c$make_outcome_data(exp=c$instrument_raw, p_exp=1)
c$harmonised_dat(exp=c$instrument_raw, out=c$instrument_outcome)
c$perform_basic_sem()

c$make_outcome_data(exp=c$standardised_exposure, p_exp=1)
c$harmonised_dat(exp=c$standardised_exposure, out=c$instrument_outcome)
c$perform_basic_sem()

suppressMessages(c$extract_instrument_regions())
c$scan_regional_instruments()
c$plot_regional_instruments(instruments=c$instrument_maxz)

c$estimate_instrument_specificity(c$instrument_maxz)
c$standardise_units(exp=c$instrument_maxz)
c$estimate_instrument_specificity(c$standardised_exposure)

c$make_outcome_data(exp=c$standardised_exposure, p_exp=1)
c$harmonised_dat(exp=c$standardised_exposure, out=c$instrument_outcome)
c$perform_basic_sem()

suppressWarnings(c$regional_ld_matrices())
suppressWarnings(c$susie_finemap_regions())
c$estimate_instrument_specificity(c$instrument_susie)
c$standardise_units(exp=c$instrument_susie)
c$make_outcome_data(exp=c$standardised_exposure, p_exp=1)
c$harmonised_dat(exp=c$standardised_exposure, out=c$instrument_outcome)
c$perform_basic_sem()
```




## Triglyceride-BMI
```r
#lavaan WARNING: some observed variances are (at least) a factor 1000 times larger than others; use varTable(fit) to investigate  
d <- MultiAncestrySummarySet$new(
  exposure_ids=c("ieu-a-302", "bbj-a-55"), 
  outcome_ids=c("ieu-a-2", "bbj-a-1"), 
  bfiles=c("/work/yc16575/1kg_imp_gwasglue/EUR", "/work/yc16575/1kg_imp_gwasglue/EAS"), 
  plink = genetics.binaRies::get_plink_binary(), 
  radius=50000, 
  clump_pop="EAS"
)
d$extract_instruments()
d$check_instruments()
d$estimate_instrument_specificity(d$instrument_raw)
suppressMessages(d$extract_instrument_regions())
d$scan_regional_instruments()
d$plot_regional_instruments(instruments=d$instrument_maxz)
d$estimate_instrument_specificity(d$instrument_maxz)
d$extract_outcome_data(exp=d$instrument_raw, p_exp=1)
d$perform_basic_sem()

d$extract_outcome_data(exp=d$instrument_maxz, p_exp=1)
d$perform_basic_sem()
```


## Smoking-lung cancer
```r
#lavaan WARNING: some observed variances are (at least) a factor 1000 times larger than others; use varTable(fit) to investigate  
d <- MultiAncestrySummarySet$new(
  exposure_ids=c("ukb-a-236", "bbj-a-78"), 
  outcome_ids=c("ukb-a-54", "bbj-a-133"), 
  bfiles=c("/work/yc16575/1kg_imp_gwasglue/EUR", "/work/yc16575/1kg_imp_gwasglue/EAS"), 
  plink = genetics.binaRies::get_plink_binary(), 
  radius=50000, 
  clump_pop="EAS"
)
d$extract_instruments()
d$check_instruments()
d$estimate_instrument_specificity(d$instrument_raw)
suppressMessages(d$extract_instrument_regions())
d$scan_regional_instruments()
d$plot_regional_instruments(instruments=d$instrument_maxz)
d$estimate_instrument_specificity(d$instrument_maxz)
d$extract_outcome_data(exp=d$instrument_raw, p_exp=1)
d$perform_basic_sem()

d$extract_outcome_data(exp=d$instrument_maxz, p_exp=1)
d$perform_basic_sem()
```
