---
title: "Emperical anlaysis"
author: "Yoonsu Cho"
date: "23/04/2021"
output: html_document
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  cache = TRUE
)
```

# Call the package
```{r}
library(MR.TRAM)
```

# Exposures: BMI (EUR-EAS); Outcomes: CHD (EUR-EAS)
```{r}
x <- MultiAncestrySummarySet$new(
  exposure_ids=c("ieu-a-2", "bbj-a-1"), 
  outcome_ids=c("ieu-a-7", "bbj-a-109"), 
  bfiles=c("/work/yc16575/1kg_imp_gwasglue/EUR", "/work/yc16575/1kg_imp_gwasglue/EAS"), 
  plink = genetics.binaRies::get_plink_binary(), 
  radius=50000, 
  clump_pop="EAS"
)
x$extract_instruments()
x$check_instruments()
x$estimate_instrument_specificity(x$instrument_raw)
x$extract_instrument_regions()
x$scan_regional_instruments()
x$estimate_instrument_specificity(x$instrument_maxz)
x$extract_outcome_data(exp=x$instrument_raw, standardise = T, p_exp=1)
x$perform_basic_sem()

x$extract_outcome_data(exp=x$instrument_maxz, standardise = T, p_exp=1)
x$perform_basic_sem()

```


# Exposures: Smoking (EUR-EAS); Outcomes: CHD (EUR-EAS)
```{r}
rm(list=ls())
y <- MultiAncestrySummarySet$new(
  exposure_ids=c("ukb-d-20116_0", "bbj-a-78"), 
  outcome_ids=c("ieu-a-7", "bbj-a-109"), 
  bfiles=c("/work/yc16575/1kg_imp_gwasglue/EUR", "/work/yc16575/1kg_imp_gwasglue/EAS"), 
  plink = genetics.binaRies::get_plink_binary(),
  radius=50000, 
  clump_pop="EAS"
)
y$extract_instruments()
y$check_instruments()
y$estimate_instrument_specificity(y$instrument_raw)
y$extract_instrument_regions()
y$scan_regional_instruments()
y$plot_regional_instruments(instruments=y$instrument_maxz)
y$estimate_instrument_specificity(y$instrument_maxz)

# Run SEM model
y$extract_outcome_data(exp=y$instrument_raw, p_exp=1)
y$perform_basic_sem()

y$extract_outcome_data(exp=y$instrument_maxz, p_exp=1)
y$perform_basic_sem()

```


# Exposures: SBP (EUR-EAS); Outcomes: CHD (EUR-EAS)
```{r}
rm(list=ls())
z <- MultiAncestrySummarySet$new(
  exposure_ids=c("ukb-b-20175", "bbj-a-52"), 
  outcome_ids=c("ieu-a-7", "bbj-a-109"), 
  bfiles=c("/work/yc16575/1kg_imp_gwasglue/EUR", "/work/yc16575/1kg_imp_gwasglue/EAS"), 
  plink = genetics.binaRies::get_plink_binary(), 
  radius=50000, 
  clump_pop="EAS"
)
z$extract_instruments()
z$check_instruments()
z$estimate_instrument_specificity(z$instrument_raw)
z$extract_instrument_regions()
z$scan_regional_instruments()
z$plot_regional_instruments(instruments=z$instrument_maxz)
z$estimate_instrument_specificity(z$instrument_maxz)
z$extract_outcome_data(exp=z$instrument_raw, p_exp=1)
z$perform_basic_sem()

z$extract_outcome_data(exp=z$instrument_maxz, p_exp=1)
z$perform_basic_sem()

```

# Smoking and CHD
```{r}
rm(list=ls())
a <- MultiAncestrySummarySet$new(
  exposure_ids=c("ukb-d-20116_0", "bbj-a-78"), 
  outcome_ids=c("ieu-a-7", "bbj-a-109"), 
  bfiles=c("/work/yc16575/1kg_imp_gwasglue/EUR", "/work/yc16575/1kg_imp_gwasglue/EAS"), 
  plink = genetics.binaRies::get_plink_binary(), 
  radius=50000, 
  clump_pop="EAS"
)
a$extract_instruments()
a$check_instruments()
a$estimate_instrument_specificity(a$instrument_raw)
a$extract_instrument_regions()
a$scan_regional_instruments()
a$plot_regional_instruments(instruments=a$instrument_maxz)
a$estimate_instrument_specificity(a$instrument_maxz)
a$extract_outcome_data(exp=a$instrument_raw, p_exp=1)
a$perform_basic_sem()

a$extract_outcome_data(exp=a$instrument_maxz, p_exp=1)
a$perform_basic_sem()
```

# BMI and CHD
```{r}
rm(list=ls())

b <- MultiAncestrySummarySet$new(
  exposure_ids=c("ukb-b-19953", "bbj-a-1"), 
  outcome_ids=c("ieu-a-7", "bbj-a-109"), 
  bfiles=c("/work/yc16575/1kg_imp_gwasglue/EUR", "/work/yc16575/1kg_imp_gwasglue/EAS"), 
  plink = genetics.binaRies::get_plink_binary(), 
  radius=50000, 
  clump_pop="EAS"
)
b$extract_instruments()
b$check_instruments()
b$estimate_instrument_specificity(b$instrument_raw)
b$extract_instrument_regions()
b$scan_regional_instruments()
b$plot_regional_instruments(instruments=b$instrument_maxz)
b$estimate_instrument_specificity(b$instrument_maxz)
b$extract_outcome_data(exp=b$instrument_raw, p_exp=1)
b$perform_basic_sem()

b$extract_outcome_data(exp=b$instrument_maxz, p_exp=1)
b$perform_basic_sem()
```

# Alcohol and BMI
```{r}
c <- MultiAncestrySummarySet$new(
  exposure_ids=c("ukb-b-5779", "ukb-e-1558_EAS"), 
  outcome_ids=c("ieu-a-2", "bbj-a-1"), 
  bfiles=c("/work/yc16575/1kg_imp_gwasglue/EUR", "/work/yc16575/1kg_imp_gwasglue/EAS"), 
  plink = genetics.binaRies::get_plink_binary(), 
  radius=50000, 
  clump_pop="EAS"
)
c$extract_instruments()
c$check_instruments()
c$estimate_instrument_specificity(c$instrument_raw)
c$extract_instrument_regions()
c$scan_regional_instruments()
c$plot_regional_instruments(instruments=c$instrument_maxz)
c$estimate_instrument_specificity(c$instrument_maxz)
c$extract_outcome_data(exp=c$instrument_raw, p_exp=1)
c$perform_basic_sem()

c$extract_outcome_data(exp=c$instrument_maxz, p_exp=1)
c$perform_basic_sem()
```
